### ISSUE TITLE
Can't get Postgres running

### ISSUE THREAD

**Issue by ralphos** [RubyoffRails/Episode3#1]
I'm having some difficulty getting postgres running.

I already had postgres installed & working (via Brew) but then I upgraded to Lion about 2 weeks ago. I haven't been able to get postgres running since then. 

I've since tried to uninstall postgres and install it again via brew. What I'm guessing is the user is still there because:

If I do `ps aux | grep post`

I get  `ralphwintle    42373   0.0  0.0  2425480    272 s000  R+    9:26PM   0:00.00 grep post`

but  `pg_ctl -D /usr/local/var/postgres status`

gives me `pg_ctl: no server running`.

I've also tried changing my top PATH to /usr/local/bin (as per Brew Doctor's suggestion) in my .zshrc file but it doesn't seem to work. If I do `which psql` is still gives me `/usr/bin/psql`.

I feel like I'm close but I just don't know enough to understand what's actually going on and debug it!

Any help would be much appreciated!

**Comment by telemachus** [comment]
The notes you get if you run `brew notes postgresql` may help. You might need to manually kickstart the database (with `initdb /usr/local/var/postgres`) or unload the old LaunchAgent and replace it with a new one.

As far as your `PATH` goes, what does `echo $PATH` show? If `/usr/local` is before `/usr/bin` (as it should be), then maybe Homebrew's postgresql is not actually installed?

(PS - What you're seeing when you run `ps aux | grep post` is the `grep` process itself. It's not telling you that the postgresql user exists, but just that the only item with the pattern `post` in your `ps aux` output is the `grep` itself.)

**Comment by ralphos** [comment]
Thanks for the tips.

I checked the brew notes via ```brew info postgres and played around with setting my top PATH which seems to be OK now. 

If I do `which postgres` is gives me `/usr/local/bin/postgres`

echo $PATH shows 
`/Users/ralphwintle/.rvm/gems/ruby-1.9.3-p125/bin:/Users/ralphwintle/.rvm/gems/ruby-1.9.3-p125@global/bin:/Users/ralphwintle/.rvm/rubies/ruby-1.9.3-p125/bin:/Users/ralphwintle/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin`which I'm not sure is altogether correct...

When I try to connect to pqsl I get that "psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?"

error but even when running the script from http://nextmarvel.net/blog/2011/09/brew-install-postgresql-on-os-x-lion/ it doesn't work.

Any ideas?

I tried `initdb /usr/local/var/postgres` and it told me `initdb: directory "/usr/local/var/postgres" exists but is not empty`

which I'm guessing is from my previous installation where it was working fine.

**Comment by telemachus** [comment]
If you can't connect to `psql`, then Postgres probably isn't running. After the Homebrew install, it's installed but not running (by default). You have two options if you want to start it:
- Automatically start at boot. (I'm going to skip this, but see the `brew info postgresql` notes for how to do it if you want.)
- Manually start the server:
  
  ```
  pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
  ```

Try to start it that way.

**Comment by ralphos** [comment]
yeh I've tried that but all I get is:

pg_ctl: another server might be running; trying to start server anyway
server starting

I when I try to stop it it says there is no such process.

**Comment by telemachus** [comment]
Last ditch idea: Uninstall Homebrew's `postgresql`, and then completely delete the directory `/usr/local/var/postres` and then start again.
- Install
- Initialize the database
- Etc.

But I'm completely grasping at straws now. Sorry.

**Comment by jwo** [comment]
Are you still having trouble?

**Comment by ralphos** [comment]
Yes, I'm still not sure how to get Postgres running. I haven't tried Peter's above suggestion or completely deleting the directory and starting again. Should I try that or book some office-hours and wait for that?

**Comment by jwo** [comment]
I've seen some people report needing to add "server: localhost" to the config/database.yml ... 

Also, after reading above, it looks like postgres is not running on your machine, but `/usr/local/var/postgres` was setup once for it.

I would:
1. delete /usr/local/var/postgres completely
2. Use postgresapp -- you should start it up and run it each time you want to use postgres.

**Comment by ralphos** [comment]
So should I just do:

rm -rf /usr/local/var/postgres

Do I need to delete users or anything else before using the postgresapp?

**Comment by jwo** [comment]
Right exactly, you might need to sudo that rm... 

Note that this will delete all of your pg data , so you don't need to delete any users

**Comment by ralphos** [comment]
Yay! I got postgres running. I admit there was something about me not being able to get it running via homebrew that was bugging me, but that postgresapp made it a breeze. 

I tried running `ruby watchman.rb` again with the servers running and ran into a permission denied error. I added `host: 'localhost'` and that seemed to fix that but then I received a database "watchman" doesn't exist error, which I thought would have been taken care of in the Migration line you wrote in the setup.rb file? (In Rails I'm assuming you'd run rake db:create or rake db:migrate but those commands won't apply here?)

**Comment by jwo** [comment]
Huzzah!

Yes, the db:create and db:migrate won't be in your rake file but you could add them :)

[These lines](https://github.com/RubyoffRails/Episode3/blob/master/db/setup.rb#L10-12) actually do the admin db creating... maybe remove the `rescue nil` and see what exception it's throwing

**Comment by ralphos** [comment]
hmm it's still the same...

`FATAL:  database "watchman" does not exist (PG::Error)`

My thinking is that I need to somehow initialize a table named watchman for it to work? I assumed that would have been taken care of by the code you highlighted above? Not sure what to do...

**Comment by jwo** [comment]
Maybe try this client (http://inductionapp.com/) and see if you can create the database. Something's not right here, I just don't know what it is.

**Comment by ralphos** [comment]
I tried the client but all that allows me to do is connect to an existing database. Therefore I couldn't do much with it.

I tried creating a rails app with postgres set up (had to add host: localhost in my config and change username) and it worked when I did rake db:create:all & rake db:migrate. 

## 

Ralph

**Comment by jwo** [comment]
Hmm, ok. So you're good to go now?

**Comment by ralphos** [comment]
Good to go for Rails development but I can't get watchman.rb running :s I booked in an office-hours session tonight. Hopefully we can try and debug a few of the issues. Have you tried teamviewer? I tried it last week, it's free and it's quite good for remote pairing, especially if you want have input on the other person's computer.
